### ISSUE TITLE
Constraint on velocity and acceleration on the bspline curve

### ISSUE THREAD

**Issue by fayyazchemban** [qnzhou/nanospline#54]
Hi. This library is really good. I was wondering how i can add constraints on the velocity and acceleration to all the control points to the bspline curve.

**Comment by qnzhou** [comment]
Can you elaborate a bit? Velocity and acceleration are mathematical properties of the curve/surfaces, are you trying to optimize the shape with respect to some constraints?

**Comment by fayyazchemban** [comment]
Hi. Thanks for your quick reply. My problem statement is that I have a list of waypoints which a robot should follow. I am trying to fit those waypoints(path) and generate a trajectory (with velocity information). I find that using C2 continuity curve like cubic spline will give both velocity and acceleration continuity to the curve and hence it will be a smooth trajectory for the robot. I wanted features like arc length parameterization, query point, maximum curvature constraint which your library is providing. I was wondering if i could also incorporate a maximum velocity and acceleration constraint (i don't have desired velocity at every control points to use cubic hermite spline) as i know the maximum limit of the robot. I could use this trajectory as a reference for a controller like model predictive control for reference trajectory tracking.

**Comment by qnzhou** [comment]
I see, for C2 interpolating splines, I would recommend the following papers:

[1] Yan, Zhipei, et al. "[K-curves: Interpolation at local maximum curvature.](https://zhipeiyan.github.io/projects/kCurves/kCurves.pdf)" ACM Transactions on Graphics (TOG) 36.4 (2017): 1-7.

[2] Yuksel, Cem. "[A class of C 2 interpolating splines.](http://www.cemyuksel.com/research/interpolating_curves/)" ACM Transactions on Graphics (TOG) 39.5 (2020): 1-14.

The first work is nearly G2 everywhere, and it is polynomial.  The second work is C2 everywhere, but non-polynomial. Unfortunately, nanospline does not have implementation of these works yet.

**Comment by fayyazchemban** [comment]
Thanks for the references. I decided to split trajectory from spline and implement differently. I liked the interface for getting arc_length and approximate_inverse_evaluate() feature in your library (i hope it is computationally faster) and hence will be using your library. But i have found an issue that i can't declare Bspline as you have defined in your documentation. 
#include <nanospline/BSpline.h>

// Construct a 2D cubic B-spline curve
nanospline::BSpline<double, 2, 3> curve;

// Setting control points. Assuming `ctrl_pts` is a nx2 Eigen matrix.
curve.set_control_points(ctrl_pts);

// Setting knots.  Assuming `knots` is a mx1 Eigen matrix.
// Where m = n+p+1, and `p` is the degree of the curve.
curve.set_knots(knots);

It gives me segmentation fault as m_control_points matrix is of size 0. I am able to get splines only from bezier but as i have a lot of waypoints, it might not be faster to have biezer curves for every four points and make new spline out of it. Is it a bug or am i doing something wrong ?
